"""add puzzles table

Revision ID: cc9582956e5e
Revises: 0001
Create Date: 2026-09-26 20:42:13.939421

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9582956e5e'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fen', sa.Text(), nullable=False),
    sa.Column('solution_uci', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also detected pre-existing index-uniqueness drift on
    # player_stats/reviews/users (unique=False in DB vs unique=True on the
    # model) left over from migration 0001. That drift is unrelated to this
    # puzzles-table migration, so those ops were intentionally stripped out
    # here rather than applied blindly — flagging for a separate migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzles')
    # ### end Alembic commands ###
